In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1,2,3],[4,5,6]],dtype=complex)

In [10]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [12]:
mdarray = np.array([1,-2,3],dtype=np.uint8)

In [13]:
mdarray

array([  1, 254,   3], dtype=uint8)

In [14]:
arry1 = np.array([1,2,3])
arry2 = np.array([1,2,3])

In [15]:
arry1 + arry2

array([2, 4, 6])

In [16]:
arry1 - arry2

array([0, 0, 0])

In [18]:
arry1 = np.array([[1,2,3],[4,5,6]])
arry2 = np.array([1,2,3])

In [20]:
arry1.shape

(2, 3)

In [21]:
arry2.shape

(3,)

In [23]:
arry3 = np.array([[1,2,3],[2,4,5],[3,3,3]])

In [24]:
arry3.shape

(3, 3)

In [25]:
arry3

array([[1, 2, 3],
       [2, 4, 5],
       [3, 3, 3]])

In [26]:
arry3[-1]

array([3, 3, 3])

In [27]:
arry3[0][2]

3

In [28]:
arry3[:-1]

array([[1, 2, 3],
       [2, 4, 5]])

In [30]:
arry3[-2:]

array([[2, 4, 5],
       [3, 3, 3]])

In [35]:
arry3[0:2,1:] #arry[行,列]

array([[2, 3],
       [4, 5]])

In [37]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [38]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [43]:
shape = (3,4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
shape1 = (3,4)
np.ones(shape1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(3,4)

array([[0.06785058, 0.3245743 , 0.6028799 , 0.44284592],
       [0.22880774, 0.31671691, 0.40452912, 0.54653214],
       [0.753918  , 0.87155687, 0.35576115, 0.24030447]])

In [63]:
np.random.seed(4)
np.random.rand()

0.9670298390136767

In [64]:
np.random.randint(1,10,(2,3))

array([[8, 6, 2],
       [9, 8, 9]])

In [69]:
a=[1,2,3]
np.random.choice(a)

2