In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1,2,3],[4,5,6]],dtype=complex)

In [10]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [12]:
mdarray = np.array([1,-2,3],dtype=np.uint8)

In [13]:
mdarray

array([  1, 254,   3], dtype=uint8)

In [14]:
arry1 = np.array([1,2,3])
arry2 = np.array([1,2,3])

In [15]:
arry1 + arry2

array([2, 4, 6])

In [16]:
arry1 - arry2

array([0, 0, 0])