In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1,2,3],[4,5,6]],dtype=complex)

In [10]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [12]:
mdarray = np.array([1,-2,3],dtype=np.uint8)

In [13]:
mdarray

array([  1, 254,   3], dtype=uint8)

In [14]:
arry1 = np.array([1,2,3])
arry2 = np.array([1,2,3])

In [15]:
arry1 + arry2

array([2, 4, 6])

In [16]:
arry1 - arry2

array([0, 0, 0])

In [18]:
arry1 = np.array([[1,2,3],[4,5,6]])
arry2 = np.array([1,2,3])

In [20]:
arry1.shape

(2, 3)

In [21]:
arry2.shape

(3,)

In [23]:
arry3 = np.array([[1,2,3],[2,4,5],[3,3,3]])

In [24]:
arry3.shape

(3, 3)

In [25]:
arry3

array([[1, 2, 3],
       [2, 4, 5],
       [3, 3, 3]])

In [26]:
arry3[-1]

array([3, 3, 3])

In [27]:
arry3[0][2]

3

In [28]:
arry3[:-1]

array([[1, 2, 3],
       [2, 4, 5]])

In [30]:
arry3[-2:]

array([[2, 4, 5],
       [3, 3, 3]])

In [35]:
arry3[0:2,1:] #arry[行,列]

array([[2, 3],
       [4, 5]])

In [37]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [38]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [43]:
shape = (3,4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
shape1 = (3,4)
np.ones(shape1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(3,4)

array([[0.06785058, 0.3245743 , 0.6028799 , 0.44284592],
       [0.22880774, 0.31671691, 0.40452912, 0.54653214],
       [0.753918  , 0.87155687, 0.35576115, 0.24030447]])

In [63]:
np.random.seed(4)
np.random.rand()

0.9670298390136767

In [64]:
np.random.randint(1,10,(2,3))

array([[8, 6, 2],
       [9, 8, 9]])

In [69]:
a=[1,2,3]
np.random.choice(a)

2

In [78]:
std_norm = np.random.randn(5,5)
std_norm

array([[-1.36735395,  1.58509564, -1.42901032, -1.62232121, -0.4290878 ],
       [-1.62606267, -1.75784563, -0.71706825,  0.21258137,  0.88797378],
       [ 1.15788279, -0.48592231,  1.03849998,  0.150796  , -0.59486708],
       [ 0.34128327, -0.49442359, -0.41224719,  1.32834536, -0.05362094],
       [ 0.68767448,  0.77821729,  0.80953263, -0.51108662,  0.04746629]])

In [75]:
#std_norm.max()

In [82]:
std_norm.argmax()

1

In [85]:
std_norm = np.random.randn(5,5)
std_norm

array([[ 0.92968507,  0.46020847, -0.18758147,  0.12080317, -0.86575871],
       [ 0.42570543,  0.12781184, -0.42330897, -0.5292739 , -1.19528179],
       [-0.82327108, -0.72200832, -0.35536086, -0.32020251, -0.08488769],
       [ 0.664241  ,  0.05629102,  2.08880579, -0.92323656,  0.64454708],
       [ 0.16629392,  0.76325686,  0.55106756,  0.667471  , -0.26889635]])

In [86]:
std_norm.max()

2.088805790207947

In [87]:
std_norm.argmax()

17

In [88]:
std_norm.min()

-1.195281786904999

In [89]:
std_norm.argmin()

9

In [90]:
std_norm.mean()

0.03868479917267668

In [92]:
np.median(std_norm)

0.0562910248200538

In [93]:
std_norm.std()

0.7173756285096994

In [94]:
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [95]:
np.log(np.linspace(1,10,10))

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [96]:
np.exp(np.linspace(1,10,10))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [97]:
np.abs([-1,2,3,-34])

array([ 1,  2,  3, 34])

In [98]:
np.clip([1,2,3,4,5,6,7,8,9],3,5)

array([3, 3, 3, 4, 5, 5, 5, 5, 5])

In [105]:
ndarray = np.arange(10)
print(ndarray)
np.where(ndarray>4,1,0)

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [106]:
array = [1,1,1,1,1,2,2,2,3,3,3,4]
np.unique(array)

array([1, 2, 3, 4])

In [107]:
array.T

AttributeError: 'list' object has no attribute 'T'

In [108]:
array = np.random.randn(5,6)

In [109]:
array

array([[-0.36440042, -1.24660636, -0.84751893,  1.20836238, -0.48781516,
        -0.60671494],
       [-1.07941927, -1.62565258, -0.60386752, -0.3680443 , -1.55546873,
        -0.25248386],
       [-1.38057624,  0.29332976,  0.65937887,  0.01674794,  0.46245999,
        -0.13049162],
       [ 0.07445564, -0.67551354,  0.46569634,  0.10064968,  0.02062567,
         0.80410996],
       [-0.02987206,  0.71906879, -1.03479122,  0.51681073,  1.07428154,
        -0.18478572]])

In [110]:
array.T

array([[-0.36440042, -1.07941927, -1.38057624,  0.07445564, -0.02987206],
       [-1.24660636, -1.62565258,  0.29332976, -0.67551354,  0.71906879],
       [-0.84751893, -0.60386752,  0.65937887,  0.46569634, -1.03479122],
       [ 1.20836238, -0.3680443 ,  0.01674794,  0.10064968,  0.51681073],
       [-0.48781516, -1.55546873,  0.46245999,  0.02062567,  1.07428154],
       [-0.60671494, -0.25248386, -0.13049162,  0.80410996, -0.18478572]])

In [111]:
np.save('sample_filepath',array.T)

In [113]:
np.load('sample_filepath.npy')

array([[-0.36440042, -1.07941927, -1.38057624,  0.07445564, -0.02987206],
       [-1.24660636, -1.62565258,  0.29332976, -0.67551354,  0.71906879],
       [-0.84751893, -0.60386752,  0.65937887,  0.46569634, -1.03479122],
       [ 1.20836238, -0.3680443 ,  0.01674794,  0.10064968,  0.51681073],
       [-0.48781516, -1.55546873,  0.46245999,  0.02062567,  1.07428154],
       [-0.60671494, -0.25248386, -0.13049162,  0.80410996, -0.18478572]])

In [114]:
dictionary = {
    'id': 123456,
    'image': np.array([1, 2, 3])
}
file_path = 'sample_dict.npy'
np.save(file_path, dictionary)

In [115]:
load_dict = np.load(file_path,allow_pickle=True)

In [116]:
load_dict

array({'id': 123456, 'image': array([1, 2, 3])}, dtype=object)

In [117]:
load_dict[()]

{'id': 123456, 'image': array([1, 2, 3])}